[package]
name = "treesize"
version = "0.3.0"
authors = [ "melak47 <melak47@gmail.com>" ]
description = "List directory tree, sorted by size"
repository = "https://github.com/melak47/treesize-rs"
license = "MIT"

[dependencies]
tabwriter = "0.1"
clap = "2"
